package com.designmyecon.shipping.Shipping.model.enums;

public enum MailClass {
    PARCEL_SELECT,
    PARCEL_SELECT_LIGHTWEIGHT,
    PRIORITY_MAIL_EXPRESS,
    PRIORITY_MAIL,
    FIRST_CLASS_PACKAGE_SERVICE,
    LIBRARY_MAIL,
    MEDIA_MAIL,
    BOUND_PRINTED_MATTER,
    USPS_CONNECT_LOCAL,
    USPS_CONNECT_MAIL,
    USPS_CONNECT_REGIONAL,
    USPS_GROUND_ADVANTAGE,
    USPS_GROUND_ADVANTAGE_RETURN_SERVICE,
    USPS_RETAIL_GROUND,
    GROUND_RETURN_SERVICE,
    FIRST_CLASS_PACKAGE_RETURN_SERVICE,
    PRIORITY_MAIL_RETURN_SERVICE,
    PRIORITY_MAIL_EXPRESS_RETURN_SERVICE;
}